name: PHP-CS-Fixer

on:
  pull_request:

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run PHP-CS-Fixer (dry run)
        uses: docker://ghcr.io/php-cs-fixer/php-cs-fixer:3-php8.2
        with:
          args: check . --diff --verbose

      - name: Apply PHP-CS-Fixer fixes
        uses: docker://ghcr.io/php-cs-fixer/php-cs-fixer:3-php8.2
        with:
          args: fix .

      - name: Commit and push changes
        if: github.event_name == 'pull_request'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Apply PHP-CS-Fixer fixes [skip ci]" && git push)
